gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0001-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0002-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0003-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0004-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0005-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0006-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0007-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0008-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0009-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0010-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0011-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0012-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0013-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0014-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0015-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0016-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0017-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0018-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0019-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0020-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0021-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0022-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0023-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0024-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0025-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0026-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0027-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0028-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0029-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0030-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0031-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0032-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0033-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0034-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0035-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0036-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0037-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0038-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0039-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0040-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0041-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0042-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0043-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0044-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0045-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0046-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0047-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0048-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0049-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0050-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0051-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0052-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0053-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0054-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0055-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0056-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0057-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0058-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0059-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0060-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0061-MP.tex
gsed -i 's/\\newcommand{\\issnppub}{.*/\\newcommand{\\issnppub}{}/g'	PNLD0062-MP.tex