gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0001-01.png}/g'	PNLD0001-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0002-01.png}/g'	PNLD0002-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0003-01.png}/g'	PNLD0003-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0004-01.png}/g'	PNLD0004-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0005-01.png}/g'	PNLD0005-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0006-01.png}/g'	PNLD0006-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0007-01.png}/g'	PNLD0007-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0008-01.png}/g'	PNLD0008-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0009-01.png}/g'	PNLD0009-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0010-01.png}/g'	PNLD0010-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0011-01.png}/g'	PNLD0011-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0012-01.png}/g'	PNLD0012-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0013-01.png}/g'	PNLD0013-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0014-01.png}/g'	PNLD0014-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0015-01.png}/g'	PNLD0015-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0016-01.png}/g'	PNLD0016-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0017-01.png}/g'	PNLD0017-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0018-01.png}/g'	PNLD0018-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0019-01.png}/g'	PNLD0019-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0020-01.png}/g'	PNLD0020-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0021-01.png}/g'	PNLD0021-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0022-01.png}/g'	PNLD0022-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0023-01.png}/g'	PNLD0023-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0024-01.png}/g'	PNLD0024-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0025-01.png}/g'	PNLD0025-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0026-01.png}/g'	PNLD0026-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0027-01.png}/g'	PNLD0027-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0028-01.png}/g'	PNLD0028-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0029-01.png}/g'	PNLD0029-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0030-01.png}/g'	PNLD0030-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0031-01.png}/g'	PNLD0031-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0032-01.png}/g'	PNLD0032-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0033-01.png}/g'	PNLD0033-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0034-01.png}/g'	PNLD0034-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0035-01.png}/g'	PNLD0035-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0036-01.png}/g'	PNLD0036-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0037-01.png}/g'	PNLD0037-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0038-01.png}/g'	PNLD0038-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0039-01.png}/g'	PNLD0039-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0040-01.png}/g'	PNLD0040-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0041-01.png}/g'	PNLD0041-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0042-01.png}/g'	PNLD0042-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0043-01.png}/g'	PNLD0043-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0044-01.png}/g'	PNLD0044-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0045-01.png}/g'	PNLD0045-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0046-01.png}/g'	PNLD0046-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0047-01.png}/g'	PNLD0047-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0048-01.png}/g'	PNLD0048-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0049-01.png}/g'	PNLD0049-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0050-01.png}/g'	PNLD0050-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0051-01.png}/g'	PNLD0051-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0052-01.png}/g'	PNLD0052-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0053-01.png}/g'	PNLD0053-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0054-01.png}/g'	PNLD0054-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0055-01.png}/g'	PNLD0055-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0056-01.png}/g'	PNLD0056-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0057-01.png}/g'	PNLD0057-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0058-01.png}/g'	PNLD0058-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0059-01.png}/g'	PNLD0059-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0060-01.png}/g'	PNLD0060-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0061-01.png}/g'	PNLD0061-MP.tex
gsed -i 's/\\newcommand{\\imagemCapa}{.*/\\newcommand{\\imagemCapa}{PNLD0062-01.png}/g'	PNLD0062-MP.tex